#!/bin/bash

# Creat configuration files

mkdir -p /opt/config
echo "__nexus_repo__" > /opt/config/nexus_repo.txt
echo "__nexus_docker_repo__" > /opt/config/nexus_docker_repo.txt
echo "__nexus_username__" > /opt/config/nexus_username.txt
echo "__nexus_password__" > /opt/config/nexus_password.txt
echo "__artifacts_version__" > /opt/config/artifacts_version.txt
echo "__dns_ip_addr__" > /opt/config/dns_ip_addr.txt
echo "__dmaap_topic__" > /opt/config/dmaap_topic.txt
echo "__openstack_username__" > /opt/config/openstack_username.txt
echo "__openstack_tenant_id__" > /opt/config/tenant_id.txt
echo "__openstack_api_key__" > /opt/config/openstack_api_key.txt
echo "__keystone_url__" > /opt/config/keystone.txt
echo "__docker_version__" > /opt/config/docker_version.txt
echo "__gerrit_branch__" > /opt/config/gerrit_branch.txt
echo "__cloud_env__" > /opt/config/cloud_env.txt

# Download and run install script
curl -k __nexus_repo__/org.openecomp.demo/boot/__artifacts_version__/mso_install.sh
cd /opt
chmod +x mso_install.sh
./mso_install.sh
